version: "3.7"
services:
  golang:
    image: golang:alpine3.9
    volumes:
      - .:/go/src/wasm-doc:cached
    working_dir: /go/src/wasm-doc
    environment:
      - GOARCH=wasm
      - GOOS=js
    ports:
      - 8080:8080
    command:
      - /bin/sh
      - -c
      - |
        GOARCH=wasm GOOS=js go build -o main.wasm main.go
        GOOS=linux GOARCH=amd64 go run server.go
